[package]
name = "smartaudio"
version = "0.3.0"
edition = "2021"
rust-version = "1.81.0"

description = "A `no_std` Rust library for parsing the TBS smartaudio protocol"
categories = ["embedded", "no-std"]
keywords = ["smartaudio", "vtx", "embedded", "no-std", "parser"]
authors = ["Nickolai Novik <nickolainovik@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/jettify/smartaudio"
repository = "https://github.com/jettify/smartaudio"
documentation = "https://docs.rs/smartaudio"
readme = "README.md"
include = [
  "src/**",
  "examples/**",
  "README.md",
  "LICENSE",
  "CHANGELOG.md",
  "Cargo.toml",
]

[dependencies]
defmt = { version = "1.0.1", optional = true }

[features]
defmt = ["dep:defmt"]
